name: gripper_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pybullet
  - gymnasium
  - stable-baselines3
  - matplotlib
  - pip
  - pip:
    - opencv-python
